sudo: required
dist: trusty

language: node_js
node_js:
   - "6"
   - "7"

env:
   - NODE_ENV=development

before_install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

install:
    - npm install -g bower
    - npm install
    - bower install

# Cache node dependencies
cache:
  directories:
    - node_modules
    - bower_components

script:
  - npm run linter
  - npm run test

addons:
  apt:
    packages:
      - xvfb
